baseURL = "/"
defaultContentLanguage = "en"
disqusShortname = ""
languageCode = "en-us"
theme = "anubis2"
title = "dotmind it"

[pagination]
pagerSize = 5

[params.author]
email = "me@dotmindblog.io"
location = "Rio de Janeiro"
name = "Volks"

[params]
dateFormat = "2006-01-02"
description = "dotmind indexes the essentials"
paginationSinglePost = true

colorTheme = "auto"
colorThemeSwitcher = true

copyCodeButton = true 
locale = "en-us" 
math = false # true: enable mathjax globally (default is false)
readMore = false 
readNextPosts = 2 
rssAsSocialIcon = true 
toc = true 

# Graphcomment support
graphcommentId = ""

GiscusCategory = "General"
GiscusCategoryId = "DIC_kwDOOHsFIM4CoAP8"
GiscusDataMapping = "pathname"
GiscusLazyLoad = false
GiscusRepo = "uphiago/dotmindblog"
GiscusRepoId = "R_kgDOOHsFIA"

customCSS = ["custom-css/custom1.scss", "custom-css/custom2.css"]

social = [
  {id = "docs", url = "https://gohugo.io/documentation/"},
  {id = "github", url = "https://github.com/Junyi-99/hugo-theme-anubis2"},
  {id = "linkedin", url = "https://www.linkedin.com/"},
  {id = "email", url = "example@example.com"},
  {id = "facebook", url = "#"},
  {id = "instagram", url = "#"},
  {id = "netease-music", url = "#"},
  {id = "telegram", url = "#"},
  {id = "x", url = "#"},
  {id = "youtube", url = "#"},
  {id = "bluesky", url = "#"},
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "English"

[languages.pl]
languageName = "Polski"

[[languages.pl.menu.main]]
identifier = "home"
name = "Strona Główna"
url = "/"
weight = 1

[[languages.pl.menu.main]]
identifier = "about"
name = "O Hugo"
url = "/about/"
weight = 2

[[languages.pl.menu.main]]
identifier = "tags"
name = "Tagi"
url = "/tags/"
weight = 3

[[languages.pl.menu.main]]
identifier = "archive"
name = "Archiwum"
url = "/posts/"
weight = 4

[languages.pl.params]
languageCode = "pl-pl"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos = false 
codeFences = true # tested with true and false. Both work.
noClasses = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth = 4 

[params.UmamiAnalytics]
datacache = false 
dnt = false 
enabled = true 
id = "d01ce82c-c8f4-4714-ba37-ba4899f2a885" # Website ID
shareUrl = "https://umami.xtra.science/share/Fy0goUn0b9rrxxGe/hugo-theme-anubis2.netlify.app" 
url = "https://umami.xtra.science/script.js" 

[params.GoogleAnalytics]
enabled = true
gtag = "G-32F16X8HLF"
