name: Deploy Dev to GitHub Pages

on:
  push:
    branches: [developer]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: developer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.4'
          extended: true

      - name: Get deployment URL
        id: deployment
        run: |
         echo "page_url=https://${{ github.repository_owner }}.github.io/${{ github.repository.name }}" >> $GITHUB_OUTPUT
        
      - name: Build
        run: hugo --minify --baseURL "${{ steps.deployment.outputs.page_url }}/"

      - name: Deploy to GitHub Pages (preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          commit_message: "Automatic deploy from developer branch - $(date +'%Y-%m-%d %H:%M:%S')"